command_timeout=1000
# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                         # The name of the module we are configuring is "character"
success_symbol = "[âš¡](bold yellow)"  # The "success_symbol" is set to "âœ" with color "bold green"
error_symbol = "[âš¡](bold red)" 

[directory]
truncation_length = 10
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
disabled=true

[git_status]
disabled=true


[nodejs]
disabled=true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# [time]
# time_format = "%T"
# format = "ğŸ•™ $time($style) "
# style = "bright-white"
# disabled = false
